sudo: required
services:
  - docker

before_install:
  - docker build -t wilfredlopez/react-test -f Dockerfile.dev .

script:
  - docker run wilfredlopez/react-test npm run test -- --coverage --watchAll=false
